In [1]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from webdriver_manager.chrome import ChromeDriverManager
import time 
import pandas as pd
import json

In [2]:
driver = webdriver.Chrome(ChromeDriverManager().install())
driver.get('https://www.caranddriver.com/shopping-advice/g32463239/new-ev-models-us/')
model = driver.find_elements_by_class_name('listicle-slide-hed-text')
traits = driver.find_elements_by_class_name('listicle-slide-dek ul')

cars_list = [] 
traits_list = []

for m in model:
	cars_list.append(m.get_attribute("textContent"))

for t in traits:
	traits_list.append(t.get_attribute("textContent"))

driver.quit()

====== WebDriver manager ======
Current google-chrome version is 90.0.4430
Get LATEST driver version for 90.0.4430
Driver [/Users/macpro/.wdm/drivers/chromedriver/mac64/90.0.4430.24/chromedriver] found in cache

In [3]:
cars_list = pd.DataFrame(cars_list)
traits_list = pd.DataFrame(traits_list)

cars_list['Traits'] = traits_list
cars_list = cars_list.rename(columns={0: 'Type', 'Traits': 'Data'})

In [4]:
cars_list

,Type,Data
0,Jaguar I-Pace — 76 MPGe,"Base price: $70,875 EPA fuel economy, combined..."
1,Audi e-tron Sportback — 77 MPGe,"Base price: $66,995EPA fuel economy, combined/..."
2,Audi e-tron — 78 MPGe,"Base price: $66,995EPA fuel economy, combined/..."
3,Porsche Taycan — 79 MPGe (tie),"Base price: $105,150 (Taycan 4S)EPA fuel econo..."
4,Volvo XC40 Recharge — 79 MPGe (tie),"Base price: $55,085EPA fuel economy, combined/..."
5,Polestar 2 — 92 MPGe,"Base price: $61,200EPA fuel economy, combined/..."
6,Tesla Model X — 96 MPGe,
7,Volkswagen ID.4 — 97 MPGe,"Base price: $86,190 EPA fuel economy, combined..."
8,Ford Mustang Mach-E — 100 MPGe,"Base price: $41,190EPA fuel economy, combined/..."
9,Mini Electric — 108 MPGe,"Base price: $43,995EPA fuel economy, combined/..."
10,Nissan Leaf — 111 MPGe (tie),"Base price: $30,750 EPA fuel economy, combined..."
11,Tesla Model S — 111 MPGe (tie),"Base price: $32,525 EPA fuel economy, combined..."
12,Kia Niro EV — 112 MPGe (tie),"Base price: $81,190 EPA fuel economy, combined..."
13,BMW i3 — 113 MPGe,"Base price: $39,620 EPA fuel economy, combined..."
14,Chevrolet Bolt EV — 118 MPGe,"Base price: $45,445 EPA fuel economy, combined..."
15,Hyundai Kona Electric — 120 MPGe,"Base price: $37,495EPA fuel economy, combined/..."
16,Tesla Model Y — 125 MPGe,"Base price: $38,330 EPA fuel economy, combined..."
17,Hyundai Ioniq Electric — 133 MPGe,"Base price: $62,190EPA fuel economy, combined/..."
18,Tesla Model 3 — 134 MPGe,"Base price: $34,020 EPA fuel economy, combined..."
19,,"Base price: $41,190 EPA fuel economy, combined..."

In [5]:
cars_list['Data'][6] = cars_list['Data'][7]
cars_list['Data'][7] = cars_list['Data'][8]
cars_list['Data'][8] = cars_list['Data'][9]
cars_list['Data'][9] = cars_list['Data'][10]
cars_list['Data'][10] = cars_list['Data'][11]
cars_list['Data'][11] = cars_list['Data'][12]
cars_list['Data'][12] = cars_list['Data'][13]
cars_list['Data'][13] = cars_list['Data'][14]
cars_list['Data'][14] = cars_list['Data'][15]
cars_list['Data'][15] = cars_list['Data'][16]
cars_list['Data'][16] = cars_list['Data'][17]
cars_list['Data'][17] = cars_list['Data'][18]
cars_list['Data'][18] = cars_list['Data'][19]
cars_list = cars_list.drop(19)

In [6]:
cars_list = cars_list.set_index('Type')

In [7]:
cars_list

                                                                                  Data
Type
Jaguar I-Pace — 76 MPGe              Base price: $70,875 EPA fuel economy, combined...
Audi e-tron Sportback — 77 MPGe      Base price: $66,995EPA fuel economy, combined/...
Audi e-tron — 78 MPGe                Base price: $66,995EPA fuel economy, combined/...
Porsche Taycan — 79 MPGe (tie)       Base price: $105,150 (Taycan 4S)EPA fuel econo...
Volvo XC40 Recharge — 79 MPGe (tie)  Base price: $55,085EPA fuel economy, combined/...
Polestar 2 — 92 MPGe                 Base price: $61,200EPA fuel economy, combined/...
Tesla Model X  — 96 MPGe             Base price: $86,190 EPA fuel economy, combined...
Volkswagen ID.4 — 97 MPGe            Base price: $41,190EPA fuel economy, combined/...
Ford Mustang Mach-E — 100 MPGe       Base price: $43,995EPA fuel economy, combined/...
Mini Electric — 108 MPGe             Base price: $30,750 EPA fuel economy, combined...
Nissan Leaf — 111 MPGe (tie)         Base price: $32,525 EPA fuel economy, combined...
Tesla Model S — 111 MPGe (tie)       Base price: $81,190 EPA fuel economy, combined...
Kia Niro EV — 112 MPGe (tie)         Base price: $39,620 EPA fuel economy, combined...
BMW i3 — 113 MPGe                    Base price: $45,445 EPA fuel economy, combined...
Chevrolet Bolt EV — 118 MPGe         Base price: $37,495EPA fuel economy, combined/...
Hyundai Kona Electric — 120 MPGe     Base price: $38,330 EPA fuel economy, combined...
Tesla Model Y — 125 MPGe             Base price: $62,190EPA fuel economy, combined/...
Hyundai Ioniq Electric — 133 MPGe    Base price: $34,020 EPA fuel economy, combined...
Tesla Model 3 — 134 MPGe             Base price: $41,190 EPA fuel economy, combined...

In [8]:
result = cars_list.to_json(orient = 'split')
result

'{"columns":["Data"],"index":["Jaguar I-Pace \\u2014 76 MPGe","Audi e-tron Sportback \\u2014 77 MPGe","Audi e-tron \\u2014 78 MPGe","Porsche Taycan \\u2014 79 MPGe (tie)","Volvo XC40 Recharge \\u2014 79 MPGe (tie)","Polestar 2 \\u2014 92 MPGe","Tesla Model X  \\u2014 96 MPGe","Volkswagen ID.4 \\u2014 97 MPGe","Ford Mustang Mach-E \\u2014 100 MPGe","Mini Electric \\u2014 108 MPGe","Nissan Leaf \\u2014 111 MPGe (tie)","Tesla Model S \\u2014 111 MPGe (tie)","Kia Niro EV \\u2014 112 MPGe (tie)","BMW i3 \\u2014 113 MPGe","Chevrolet Bolt EV \\u2014 118 MPGe","Hyundai Kona Electric \\u2014 120 MPGe","Tesla Model Y \\u2014 125 MPGe","Hyundai Ioniq Electric \\u2014 133 MPGe","Tesla Model 3 \\u2014 134 MPGe"],"data":[["Base price: $70,875 EPA fuel economy, combined\\/city\\/highway: 76\\/80\\/72 MPGe EPA combined range: 234 miles"],["Base price: $66,995EPA fuel economy, combined\\/city\\/highway: 77\\/76\\/78 MPGe EPA combined range: 218 miles"],["Base price: $66,995EPA fuel economy, combined\\/city\\/highway: 78\\/78\\/77 MPGe EPA combined range: 222 miles "],["Base price: $105,150 (Taycan 4S)EPA fuel economy, combined\\/city\\/highway: 79\\/79\\/80 MPGe EPA combined range: 222 miles "],["Base price: $55,085EPA fuel economy, combined\\/city\\/highway: 79\\/85\\/72 MPGe EPA combined range: 208 miles"],["Base price: $61,200EPA fuel economy, combined\\/city\\/highway: 92\\/96\\/88 MPGe EPA combined range: 233 miles "],["Base price: $86,190 EPA fuel economy, combined\\/city\\/highway: 96\\/99\\/93 MPGe EPA combined range: 328 miles"],["Base price: $41,190EPA fuel economy, combined\\/city\\/highway: 97\\/104\\/89 MPGe EPA combined range: 250 miles"],["Base price: $43,995EPA fuel economy, combined\\/city\\/highway: 100\\/105\\/93 MPGe EPA combined range: 300 miles"],["Base price: $30,750 EPA fuel economy, combined\\/city\\/highway: 108\\/115\\/100 MPGe EPA combined range: 110 miles "],["Base price: $32,525 EPA fuel economy, combined\\/city\\/highway: 111\\/123\\/99 MPGe EPA combined range: 149 miles (40 kW-hr Battery Pack)"],["Base price: $81,190 EPA fuel economy, combined\\/city\\/highway: 111\\/115\\/107 MPGe EPA combined range: 373 miles  "],["Base price: $39,620 EPA fuel economy, combined\\/city\\/highway: 112\\/123\\/102 MPGe EPA combined range: 239 miles "],["Base price: $45,445 EPA fuel economy, combined\\/city\\/highway: 113\\/124\\/102 MPGe EPA combined range: 153 miles "],["Base price: $37,495EPA fuel economy, combined\\/city\\/highway: 118\\/127\\/108 MPGe EPA combined range: 259 miles "],["Base price: $38,330 EPA fuel economy, combined\\/city\\/highway: 120\\/132\\/108 MPGe EPA combined range: 258 miles"],["Base price: $62,190EPA fuel economy, combined\\/city\\/highway: 125\\/131\\/117 MPGe EPA combined range: 326 miles (Long Range AWD)"],["Base price: $34,020 EPA fuel economy, combined\\/city\\/highway: 133\\/145\\/121 MPGe EPA combined range: 170 miles "],["Base price: $41,190 EPA fuel economy, combined\\/city\\/highway: 134\\/141\\/127 MPGe EPA combined range: 353 miles (Long Range AWD)"]]}'

In [9]:
parsed = json.loads(result)
print(parsed)

{'columns': ['Data'], 'index': ['Jaguar I-Pace — 76 MPGe', 'Audi e-tron Sportback — 77 MPGe', 'Audi e-tron — 78 MPGe', 'Porsche Taycan — 79 MPGe (tie)', 'Volvo XC40 Recharge — 79 MPGe (tie)', 'Polestar 2 — 92 MPGe', 'Tesla Model X  — 96 MPGe', 'Volkswagen ID.4 — 97 MPGe', 'Ford Mustang Mach-E — 100 MPGe', 'Mini Electric — 108 MPGe', 'Nissan Leaf — 111 MPGe (tie)', 'Tesla Model S — 111 MPGe (tie)', 'Kia Niro EV — 112 MPGe (tie)', 'BMW i3 — 113 MPGe', 'Chevrolet Bolt EV — 118 MPGe', 'Hyundai Kona Electric — 120 MPGe', 'Tesla Model Y — 125 MPGe', 'Hyundai Ioniq Electric — 133 MPGe', 'Tesla Model 3 — 134 MPGe'], 'data': [['Base price: $70,875 EPA fuel economy, combined/city/highway: 76/80/72 MPGe EPA combined range: 234 miles'], ['Base price: $66,995EPA fuel economy, combined/city/highway: 77/76/78 MPGe EPA combined range: 218 miles'], ['Base price: $66,995EPA fuel economy, combined/city/highway: 78/78/77 MPGe EPA combined range: 222 miles '], ['Base price: $105,150 (Taycan 4S)EPA fuel economy, combined/city/highway: 79/79/80 MPGe EPA combined range: 222 miles '], ['Base price: $55,085EPA fuel economy, combined/city/highway: 79/85/72 MPGe EPA combined range: 208 miles'], ['Base price: $61,200EPA fuel economy, combined/city/highway: 92/96/88 MPGe EPA combined range: 233 miles '], ['Base price: $86,190 EPA fuel economy, combined/city/highway: 96/99/93 MPGe EPA combined range: 328 miles'], ['Base price: $41,190EPA fuel economy, combined/city/highway: 97/104/89 MPGe EPA combined range: 250 miles'], ['Base price: $43,995EPA fuel economy, combined/city/highway: 100/105/93 MPGe EPA combined range: 300 miles'], ['Base price: $30,750 EPA fuel economy, combined/city/highway: 108/115/100 MPGe EPA combined range: 110 miles '], ['Base price: $32,525 EPA fuel economy, combined/city/highway: 111/123/99 MPGe EPA combined range: 149 miles (40 kW-hr Battery Pack)'], ['Base price: $81,190 EPA fuel economy, combined/city/highway: 111/115/107 MPGe EPA combined range: 373 miles  '], ['Base price: $39,620 EPA fuel economy, combined/city/highway: 112/123/102 MPGe EPA combined range: 239 miles '], ['Base price: $45,445 EPA fuel economy, combined/city/highway: 113/124/102 MPGe EPA combined range: 153 miles '], ['Base price: $37,495EPA fuel economy, combined/city/highway: 118/127/108 MPGe EPA combined range: 259 miles '], ['Base price: $38,330 EPA fuel economy, combined/city/highway: 120/132/108 MPGe EPA combined range: 258 miles'], ['Base price: $62,190EPA fuel economy, combined/city/highway: 125/131/117 MPGe EPA combined range: 326 miles (Long Range AWD)'], ['Base price: $34,020 EPA fuel economy, combined/city/highway: 133/145/121 MPGe EPA combined range: 170 miles '], ['Base price: $41,190 EPA fuel economy, combined/city/highway: 134/141/127 MPGe EPA combined range: 353 miles (Long Range AWD)']]}

In [11]:
joutput = json.dumps(parsed, indent=4)
print(joutput)

{
    "columns": [
        "Data"
    ],
    "index": [
        "Jaguar I-Pace \u2014 76 MPGe",
        "Audi e-tron Sportback \u2014 77 MPGe",
        "Audi e-tron \u2014 78 MPGe",
        "Porsche Taycan \u2014 79 MPGe (tie)",
        "Volvo XC40 Recharge \u2014 79 MPGe (tie)",
        "Polestar 2 \u2014 92 MPGe",
        "Tesla Model X  \u2014 96 MPGe",
        "Volkswagen ID.4 \u2014 97 MPGe",
        "Ford Mustang Mach-E \u2014 100 MPGe",
        "Mini Electric \u2014 108 MPGe",
        "Nissan Leaf \u2014 111 MPGe (tie)",
        "Tesla Model S \u2014 111 MPGe (tie)",
        "Kia Niro EV \u2014 112 MPGe (tie)",
        "BMW i3 \u2014 113 MPGe",
        "Chevrolet Bolt EV \u2014 118 MPGe",
        "Hyundai Kona Electric \u2014 120 MPGe",
        "Tesla Model Y \u2014 125 MPGe",
        "Hyundai Ioniq Electric \u2014 133 MPGe",
        "Tesla Model 3 \u2014 134 MPGe"
    ],
    "data": [
        [
            "Base price: $70,875 EPA fuel economy, combined/city/highway: 76/80/72 MPGe EPA combined range: 234 miles"
        ],
        [
            "Base price: $66,995EPA fuel economy, combined/city/highway: 77/76/78 MPGe EPA combined range: 218 miles"
        ],
        [
            "Base price: $66,995EPA fuel economy, combined/city/highway: 78/78/77 MPGe EPA combined range: 222 miles "
        ],
        [
            "Base price: $105,150 (Taycan 4S)EPA fuel economy, combined/city/highway: 79/79/80 MPGe EPA combined range: 222 miles "
        ],
        [
            "Base price: $55,085EPA fuel economy, combined/city/highway: 79/85/72 MPGe EPA combined range: 208 miles"
        ],
        [
            "Base price: $61,200EPA fuel economy, combined/city/highway: 92/96/88 MPGe EPA combined range: 233 miles "
        ],
        [
            "Base price: $86,190 EPA fuel economy, combined/city/highway: 96/99/93 MPGe EPA combined range: 328 miles"
        ],
        [
            "Base price: $41,190EPA fuel economy, combined/city/highway: 97/104/89 MPGe EPA combined range: 250 miles"
        ],
        [
            "Base price: $43,995EPA fuel economy, combined/city/highway: 100/105/93 MPGe EPA combined range: 300 miles"
        ],
        [
            "Base price: $30,750 EPA fuel economy, combined/city/highway: 108/115/100 MPGe EPA combined range: 110 miles "
        ],
        [
            "Base price: $32,525 EPA fuel economy, combined/city/highway: 111/123/99 MPGe EPA combined range: 149 miles (40 kW-hr Battery Pack)"
        ],
        [
            "Base price: $81,190 EPA fuel economy, combined/city/highway: 111/115/107 MPGe EPA combined range: 373 miles  "
        ],
        [
            "Base price: $39,620 EPA fuel economy, combined/city/highway: 112/123/102 MPGe EPA combined range: 239 miles "
        ],
        [
            "Base price: $45,445 EPA fuel economy, combined/city/highway: 113/124/102 MPGe EPA combined range: 153 miles "
        ],
        [
            "Base price: $37,495EPA fuel economy, combined/city/highway: 118/127/108 MPGe EPA combined range: 259 miles "
        ],
        [
            "Base price: $38,330 EPA fuel economy, combined/city/highway: 120/132/108 MPGe EPA combined range: 258 miles"
        ],
        [
            "Base price: $62,190EPA fuel economy, combined/city/highway: 125/131/117 MPGe EPA combined range: 326 miles (Long Range AWD)"
        ],
        [
            "Base price: $34,020 EPA fuel economy, combined/city/highway: 133/145/121 MPGe EPA combined range: 170 miles "
        ],
        [
            "Base price: $41,190 EPA fuel economy, combined/city/highway: 134/141/127 MPGe EPA combined range: 353 miles (Long Range AWD)"
        ]
    ]
}

In [13]:
f = open("jsonify.txt", "a")
f.write(joutput)
f.close()